FROM public.ecr.aws/chainguard/node:latest-dev AS builder

WORKDIR /app
COPY . .
RUN npm install

FROM public.ecr.aws/chainguard/node:latest

WORKDIR /app
COPY --from=builder ./app .
COPY . .

ENTRYPOINT ["node", "src/server.js"]